### ISSUE TITLE
Incompatible with newer Java versions

### ISSUE THREAD

**Issue by plexus** [greglook/alphabase#4]
`alphabase.hex` makes use of `javax.xml.bind.DatatypeConverter`, which on Java 9 and 10 is no longer on the classpath by default, and from Java 11 is no longer part of the JDK.

This issue explains the issue and various solutions: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j/46455026

For Java 11 the solution would be to add an explicit dependency on `javax.xml.bind/jaxb-api`, which would also solve things for Java 9 and 10.

**Comment by greglook** [comment]
I think I'll just pull out the optimization for `:clj` - this is meant to be a dependency-free lib, so if people need optimized hex conversion they can do it more directly.
